name: Notes CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission for gradlew
        run: sudo chmod +x gradlew

      - name: Run Ktlint Format
        run: ./gradlew ktlintFormat

      - name: Run Ktlint Check
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
